import json


def generate_document(doc_type, topic):
    topic = (topic or "untitled").strip().replace(" ", "_")
    if doc_type == "preprint":
        return f"""# {topic}

## Abstract
This preprint defines the topic and frames it for formal research use.

## Core Idea
Formal governed computation provides bounded, receipted transitions.

## Conclusion
This document was generated by the Formal Document Engine.
"""
    if doc_type == "whitepaper":
        return f"""# {topic} Whitepaper

## Overview
This whitepaper summarizes the architecture, motivation, and operating model.

## Architecture
Governed execution, deterministic transitions, and bundle transport.
"""
    if doc_type == "technical_spec":
        return f"""# {topic} Technical Specification

## Inputs
## Outputs
## Constraints
## Interfaces
"""
    if doc_type == "governance_model":
        return f"""# {topic} Governance Model

## Boundary
## Policy
## Escalation
## Audit
"""
    return f"# {topic}\n"
